using only commit sha for versioning

diff --git a/.github/workflows/docker-ci.yml b/.github/workflows/docker-ci.yml
--- a/.github/workflows/docker-ci.yml
+++ b/.github/workflows/docker-ci.yml
@@ -6,18 +6,6 @@ on:
     paths:
       - 'receipts_project/**'
       - '.github/**'
-
-  workflow_dispatch:
-    inputs:
-      bump_type:
-        description: "Select version bump type"
-        required: true
-        default: patch
-        type: choice
-        options:
-          - patch
-          - minor
-          - major
   
 permissions:
   contents: write # Needed to push version tags to remote repo
@@ -33,45 +21,44 @@ jobs:
         github.event_name == 'workflow_dispatch'
     outputs:
       new_image_tag: ${{ steps.bump-version.outputs.new_image_tag }}
-      new_version: ${{ steps.bump-version.outputs.new_version }}
 
     steps:
       - name: Checkout source code
         uses: actions/checkout@v4
 
-      - name: Set bump type
-        id: detect-bump
+      - name: Check current image tag from dockerhub
+        id: extract-image-tag-dockerhub
+        uses: ./.github/actions/extract-image-tag-dockerhub
+
+      - name: Echo current image tag from dockerhub
         run: |
-          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
-            echo "bump_type=${{ github.event.inputs.bump_type }}" >> $GITHUB_OUTPUT
-          else
-            COMMIT_MSG=$(git log -1 --pretty=%B)
-            if [[ "$COMMIT_MSG" == *"bump:major"* ]]; then
-              echo "bump_type=major" >> $GITHUB_OUTPUT
-            elif [[ "$COMMIT_MSG" == *"bump:minor"* ]]; then
-              echo "bump_type=minor" >> $GITHUB_OUTPUT
-            else
-              echo "bump_type=patch" >> $GITHUB_OUTPUT
-            fi
-          fi
+            echo "Current image tag from Docker Hub: ${{ steps.extract-image-tag-dockerhub.outputs.current_image_sha }}"
+            echo "CURRENT_IMAGE_SHA=${{ steps.extract-image-tag-dockerhub.outputs.current_image_sha }}" >> $GITHUB_ENV
 
       - name: Bump version
         id: bump-version
-        uses: ./.github/actions/bump-version
-        with:
-          bump-type: ${{ steps.detect-bump.outputs.bump_type }}
+        uses: ./.github/actions/bump-version-sha
 
       - name: Echo new image tag
         run: |
             echo "New image tag: ${{ steps.bump-version.outputs.new_image_tag }}"
             echo "New version: ${{ steps.bump-version.outputs.new_version }}"
 
+      - name: Fail if new image tag is the same as current
+        run: |
+            if [ "${{ steps.bump-version.outputs.new_image_tag }}" == "${{ steps.extract-image-tag-dockerhub.outputs.current_image_sha }}" ]; then
+              echo "New image tag is the same as current. Failing the job."
+              exit 1
+            else
+              echo "New image tag is different from current. Proceeding."
+            fi
+
   docker-build-push:
     runs-on: ubuntu-latest
     needs: bump-version
     if: >
         (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
-        github.event_name == 'workflow_dispatch'
+        github.event_name == 'workflow_dispatch' 
     steps:
       - name: Checkout source code
         uses: actions/checkout@v4
@@ -98,28 +85,28 @@ jobs:
           push: true
           tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.DEPLOYMENT_NAME }}:${{ needs.bump-version.outputs.new_image_tag }}
 
-  push-version-tag:
-    runs-on: ubuntu-latest
-    needs: [docker-build-push, bump-version]
-    if: >
-        (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
-        github.event_name == 'workflow_dispatch'
-    steps:
-      - name: Checkout source code
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0  # Required to get full history and tags
+  # push-version-tag:
+  #   runs-on: ubuntu-latest
+  #   needs: [docker-build-push, bump-version]
+  #   if: >
+  #       (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
+  #       github.event_name == 'workflow_dispatch'
+  #   steps:
+  #     - name: Checkout source code
+  #       uses: actions/checkout@v4
+  #       with:
+  #         fetch-depth: 0  # Required to get full history and tags
 
-      - name: Push new Git tag (if it doesn't already exist)
-        run: |
-            git config user.name "github-actions"
-            git config user.email "github-actions@github.com"
+  #     - name: Push new Git tag (if it doesn't already exist)
+  #       run: |
+  #           git config user.name "github-actions"
+  #           git config user.email "github-actions@github.com"
 
-            NEW_VERSION_TAG="${{ needs.bump-version.outputs.new_version }}"
-            if git rev-parse "$NEW_VERSION_TAG" >/dev/null 2>&1; then
-            echo "Tag $NEW_VERSION_TAG already exists. Skipping tag creation."
-            else
-            git tag "$NEW_VERSION_TAG"
-            git push origin "$NEW_VERSION_TAG"
-            fi
+  #           NEW_VERSION_TAG="${{ needs.bump-version.outputs.new_version }}"
+  #           if git rev-parse "$NEW_VERSION_TAG" >/dev/null 2>&1; then
+  #           echo "Tag $NEW_VERSION_TAG already exists. Skipping tag creation."
+  #           else
+  #           git tag "$NEW_VERSION_TAG"
+  #           git push origin "$NEW_VERSION_TAG"
+  #           fi
 
